apiVersion: v1
data:
  APP_VERSION: "{{ .Values.chiaretto.version }}"
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-version
---
apiVersion: v1
data:
  APP_ENV: "{{ .Values.env }}"
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-environment

