apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Release.name }}
    app.kubernetes.io/component: {{ .Release.name }}
    app.kubernetes.io/instance: {{ .Release.name }}
  name: {{ .Release.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: {{ .Release.name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: {{ .Release.name }}
    spec:
      containers:
      - env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              key: APP_VERSION
              name: {{ .Release.name }}-version
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: {{ .Release.name }}-environment
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              key: APP_SECRET
              name: {{ .Release.name }}-secret
        image: "quay.io/chiaretto/chiaretto-app:{{ .Values.chiaretto.version }}"
        imagePullPolicy: Always
        name: {{ .Release.name }}
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
