apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              key: APP_VERSION
              name: "{{ .Release.Name }}-version"
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: "{{ .Release.Name }}-environment"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              key: APP_SECRET
              name: app-secret
        image: "quay.io/chiaretto/chiaretto-app:{{ .Values.chiaretto.version }}"
        imagePullPolicy: Always
        name: {{ .Release.Name }}
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30