apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ Values.release.name }}
    app.kubernetes.io/component: {{ Values.release.name }}
    app.kubernetes.io/instance: {{ Values.release.name }}
  name: chiaretto-https
spec:
  host: "{{ .Values.chiaretto.route }}"
  port:
    targetPort: 8081-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ Values.release.name }}
    weight: 100
  wildcardPolicy: None
