apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: chiaretto-app-secret
  namespace: chiaretto-app
spec:
  encryptedData:
    APP_SECRET: AgBLfi4xlk0cU7mf7PpQOmLcirWUDcB9gAUm/W1WOnulwzi/ZP8BGfk0hlw90iJrVEIurwZ8ZYOApFsFtVk+X1tbvG3gYiAmGdWlbtn8wzly2axNFDpPBrX2ZDwzuKCtQD4Lg/Zygq3WyaLee1lFJhrQCx6th8+OIHbgeyeBeIYRI9/aTw70rJwOW4CjfS8E9x8FcQwYQtYdMnoehuJEsTf7VLLxcXi1vW6rN9tWn8xgBcZl0BTkYtV1m2sr++o1SAsXnMYdWohYf+5GWG7Hb1MsgKzn/5dn6NLjAeCJCMau+oaB3BhKzzCHiY1uAdkexe2LkOH6lBmJxMt21YXX7IqLW4xHQkPlp5g88SvxLg/kANQy/oDNGE6K820Ibv2tW8lEEew64eQo3ppjYv0tdpL4A4NAYt8OEHlpfJrJ8oGJ5TldsIu0ZAFVJCgAALSTA5MDLcfVLcVWDgx2wMWA0jvPBqQLMKb0pD4xxGRGkPx70shIoJZqnDAcUp9neTkYchSUg34aM868AfkqwfwHfoflxspTwu7Usj8KH5q+fS13P+Kr0ydmHDHBO2JmCGzX4utdVSy5btOhdsY0XWndOSEzHRtOHc+Ureg9VhHzzgcJP1vILP7ygAxUEbGNjOpXnYmCstN0CfDSbPRwQ+Gpg/LLedNTN4in3aK8QDBd7wElwaKRMjKDJclHfgHEIYNGUbGbgRKB53mSghraQNIa7rDge9Y=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: chiaretto-app-secret
      namespace: chiaretto-app
    type: Opaque

