apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.name }}
    app.kubernetes.io/component: {{ .Release.name }}
    app.kubernetes.io/instance: {{ .Release.name }}
  name: {{ .Release.name }}
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deploymentconfig: {{ .Release.name }}
  sessionAffinity: None
  type: ClusterIP
